# Uncomment the next line to define a global platform for your project
 platform :ios, '11.0'


source 'https://github.com/CocoaPods/Specs.git'

target 'Host' do

pod 'MethodHook', :path => '../../'


end
